/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as EspacoIdRouteImport } from './routes/espaco.$id'
import { Route as PredioIdRouteImport } from './routes/predio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoIdRoute = EspacoIdRouteImport.update({
  id: '/espaco/$id',
  path: '/espaco/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PredioIdRoute = PredioIdRouteImport.update({
  id: '/predio/$id',
  path: '/predio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/mapa': typeof MapaRoute
  '/espaco/$id': typeof EspacoIdRoute
  '/predio/$id': typeof PredioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/mapa': typeof MapaRoute
  '/espaco/$id': typeof EspacoIdRoute
  '/predio/$id': typeof PredioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/mapa': typeof MapaRoute
  '/espaco/$id': typeof EspacoIdRoute
  '/predio/$id': typeof PredioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/busca' | '/mapa' | '/espaco/$id' | '/predio/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/busca' | '/mapa' | '/espaco/$id' | '/predio/$id'
  id: '__root__' | '/' | '/busca' | '/mapa' | '/espaco/$id' | '/predio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  MapaRoute: typeof MapaRoute
  EspacoIdRoute: typeof EspacoIdRoute
  PredioIdRoute: typeof PredioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espaco/$id': {
      id: '/espaco/$id'
      path: '/espaco/$id'
      fullPath: '/espaco/$id'
      preLoaderRoute: typeof EspacoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predio/$id': {
      id: '/predio/$id'
      path: '/predio/$id'
      fullPath: '/predio/$id'
      preLoaderRoute: typeof PredioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  MapaRoute: MapaRoute,
  EspacoIdRoute: EspacoIdRoute,
  PredioIdRoute: PredioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
